
import { GradeLevel, Teacher } from "./types";

export const TEACHERS: Teacher[] = [
  // Existing Teachers (t1 - t30)
  {
    id: 't1',
    name: '부엉이 선생님',
    avatar: '🦉',
    style: '지혜롭고 차분하게 설명해주시는 스타일',
    voiceName: 'Kore',
    gender: 'female',
    color: 'bg-indigo-600',
    greeting: '안녕? 오늘도 새로운 지식을 함께 탐구해보자꾸나.',
    visualDesc: 'A wise cute owl teacher wearing glasses and a tweed suit, holding a pointer stick, full body character, 2D vector illustration, educational style',
    backgroundPrompt: 'A magical library classroom with tall bookshelves filled with ancient books, globe, warm lighting, harry potter style, 2D vector illustration'
  },
  {
    id: 't2',
    name: '호랑이 코치님',
    avatar: '🐯',
    style: '에너지 넘치고 씩씩하게 가르치는 스타일',
    voiceName: 'Fenrir',
    gender: 'male',
    color: 'bg-orange-600',
    greeting: '반갑다 친구들! 오늘도 힘차게 공부해볼까?!',
    visualDesc: 'A strong cute tiger coach wearing a tracksuit and a whistle, full body character, 2D vector illustration, energetic pose',
    backgroundPrompt: 'A school gymnasium with sports equipment, basketball hoop, wooden floor, bright and energetic atmosphere, 2D vector illustration'
  },
  {
    id: 't3',
    name: '토끼 선생님',
    avatar: '🐰',
    style: '다정하고 친절하게 동화처럼 들려주는 스타일',
    voiceName: 'Puck',
    gender: 'male',
    color: 'bg-pink-500',
    greeting: '안녕 얘들아~ 오늘은 어떤 재미있는 이야기를 해볼까?',
    visualDesc: 'A gentle cute rabbit teacher wearing a cardigan and holding a book, full body character, 2D vector illustration, soft colors',
    backgroundPrompt: 'A cozy kindergarten classroom with pastel colors, cute decorations, cushions, and storybooks, 2D vector illustration'
  },
  {
    id: 't4',
    name: '곰돌이 박사님',
    avatar: '🐻',
    style: '느긋하지만 깊이 있는 지식을 알려주는 스타일',
    voiceName: 'Charon',
    gender: 'male',
    color: 'bg-amber-700',
    greeting: '허허, 어서 오렴. 오늘은 또 어떤 궁금한 게 있니?',
    visualDesc: 'A brown bear professor wearing a lab coat and glasses, full body character, 2D vector illustration, academic style',
    backgroundPrompt: 'An academic study room with a chalkboard, stacks of books, wooden desk, warm and traditional feeling, 2D vector illustration'
  },
  {
    id: 't5',
    name: '고양이 선생님',
    avatar: '🐱',
    style: '새침하지만 꼼꼼하게 알려주는 스타일',
    voiceName: 'Zephyr',
    gender: 'female',
    color: 'bg-teal-500',
    greeting: '자, 자리에 앉았니? 수업 시작할 거야, 집중해!',
    visualDesc: 'A smart cat teacher wearing a formal blouse and skirt, full body character, 2D vector illustration, neat and clean',
    backgroundPrompt: 'A modern, clean, and organized classroom with white desks, laptop, neat whiteboard, sunlight streaming in, 2D vector illustration'
  },
  {
    id: 't6',
    name: '로봇 조교',
    avatar: '🤖',
    style: '정확하고 논리적으로 설명하는 미래지향적 스타일',
    voiceName: 'Kore',
    gender: 'female',
    color: 'bg-slate-600',
    greeting: '데이터 로딩 완료. 학습 모드를 시작합니다. 삐리릭.',
    visualDesc: 'A friendly futuristic robot teacher with a screen face, full body character, 2D vector illustration, sci-fi education',
    backgroundPrompt: 'A futuristic sci-fi classroom with holographic displays, neon lights, metallic surfaces, high-tech gadgets, 2D vector illustration'
  },
  {
    id: 't7',
    name: '강아지 선생님',
    avatar: '🐶',
    style: '활기차고 친구같은 스타일',
    voiceName: 'Puck',
    gender: 'male',
    color: 'bg-yellow-500',
    greeting: '멍멍! 아니, 안녕! 같이 재미있게 놀면서 배우자!',
    visualDesc: 'A happy golden retriever dog teacher wearing a shirt and tie, full body character, 2D vector illustration, friendly vibe',
    backgroundPrompt: 'A playful classroom with colorful blocks, toys, bright yellow walls, happy and sunny atmosphere, 2D vector illustration'
  },
  {
    id: 't8',
    name: '여우 선생님',
    avatar: '🦊',
    style: '영리하고 센스있는 설명 스타일',
    voiceName: 'Kore',
    gender: 'female',
    color: 'bg-orange-500',
    greeting: '후후, 나랑 함께라면 어려운 문제도 쉽게 풀릴 거야.',
    visualDesc: 'A clever fox teacher wearing a stylish scarf and vest, full body character, 2D vector illustration, smart look',
    backgroundPrompt: 'A stylish art room with easel, paints, colorful abstract paintings on the wall, creative atmosphere, 2D vector illustration'
  },
  {
    id: 't9',
    name: '사자 교장선생님',
    avatar: '🦁',
    style: '엄엄하지만 따뜻한 리더십 스타일',
    voiceName: 'Fenrir',
    gender: 'male',
    color: 'bg-yellow-700',
    greeting: '으르렁~ 용기를 가지고 도전하면 못할 것이 없다!',
    visualDesc: 'A majestic lion principal wearing a suit and tie, full body character, 2D vector illustration, leadership',
    backgroundPrompt: 'A grand principal office with a large mahogany desk, flags, trophies, carpet, dignified atmosphere, 2D vector illustration'
  },
  {
    id: 't10',
    name: '펭귄 선생님',
    avatar: '🐧',
    style: '귀엽고 엉뚱하지만 핵심을 찌르는 스타일',
    voiceName: 'Zephyr',
    gender: 'female',
    color: 'bg-sky-500',
    greeting: '뒤뚱뒤뚱~ 남극에서 온 지식 배달부 펭귄이야!',
    visualDesc: 'A cute penguin teacher wearing a bow tie and carrying a bag, full body character, 2D vector illustration, winter theme',
    backgroundPrompt: 'A classroom made of ice and snow, igloo style, blue and white colors, chilly but cute atmosphere, 2D vector illustration'
  },
  {
    id: 't11',
    name: '코끼리 아저씨',
    avatar: '🐘',
    style: '묵직하고 이해하기 쉽게 알려주는 스타일',
    voiceName: 'Charon',
    gender: 'male',
    color: 'bg-slate-500',
    greeting: '허허, 반갑다. 천천히 하나씩 배워보자꾸나.',
    visualDesc: 'A gentle big elephant teacher wearing a vest and bow tie, full body character, 2D vector illustration, reliable look',
    backgroundPrompt: 'A spacious classroom with large maps on the wall, big chalkboard, sturdy furniture, calm grey tones, 2D vector illustration'
  },
  {
    id: 't12',
    name: '돌고래 선생님',
    avatar: '🐬',
    style: '톡톡 튀는 상쾌한 수업 스타일',
    voiceName: 'Zephyr',
    gender: 'female',
    color: 'bg-cyan-500',
    greeting: '첨벙! 안녕 친구들? 시원시원하게 알려줄게!',
    visualDesc: 'A cheerful dolphin teacher wearing glasses and holding a tablet, full body character, 2D vector illustration, aquatic theme',
    backgroundPrompt: 'An underwater classroom with coral reefs, bubbles, blue water background, submarine windows, 2D vector illustration'
  },
  {
    id: 't13',
    name: '판다 선생님',
    avatar: '🐼',
    style: '여유롭고 편안한 예술 수업 스타일',
    voiceName: 'Charon',
    gender: 'male',
    color: 'bg-emerald-600',
    greeting: '안녕~? 천천히 마음을 비우고 그려보자.',
    visualDesc: 'A relaxed panda teacher holding a bamboo brush, wearing traditional clothes, full body character, 2D vector illustration, artistic',
    backgroundPrompt: 'A peaceful bamboo forest classroom, nature friendly, asian ink painting style, green and calm, 2D vector illustration'
  },
  {
    id: 't14',
    name: '코알라 선생님',
    avatar: '🐨',
    style: '졸린 듯하지만 핵심은 놓치지 않는 스타일',
    voiceName: 'Zephyr',
    gender: 'female',
    color: 'bg-gray-400',
    greeting: '음.. 안녕.. 같이 편하게 책 읽을까?',
    visualDesc: 'A cute koala teacher holding a pillow and a book, wearing pajamas, full body character, 2D vector illustration, cozy',
    backgroundPrompt: 'A treehouse classroom with eucalyptus leaves, hammocks, soft lighting, very cozy and sleepy atmosphere, 2D vector illustration'
  },
  {
    id: 't15',
    name: '티라노 선생님',
    avatar: '🦖',
    style: '박력 넘치는 역사 수업 스타일',
    voiceName: 'Fenrir',
    gender: 'male',
    color: 'bg-green-700',
    greeting: '크앙! 과거의 비밀을 파헤쳐 보자!',
    visualDesc: 'A cute T-rex dinosaur teacher wearing an archaeologist hat and vest, full body character, 2D vector illustration, adventurous',
    backgroundPrompt: 'A history museum classroom with dinosaur fossils, ancient relics, jungle plants, exciting atmosphere, 2D vector illustration'
  },
  {
    id: 't16',
    name: '양 선생님',
    avatar: '🐑',
    style: '포근하고 따뜻한 상담 선생님 스타일',
    voiceName: 'Puck',
    gender: 'female',
    color: 'bg-rose-300',
    greeting: '어서 와, 고민이 있니? 선생님이 들어줄게.',
    visualDesc: 'A fluffy sheep teacher wearing a pink apron and knitting, full body character, 2D vector illustration, motherly',
    backgroundPrompt: 'A classroom in the clouds, fluffy white clouds, pastel sky, soft wool textures, dreamy atmosphere, 2D vector illustration'
  },
  {
    id: 't17',
    name: '독수리 선생님',
    avatar: '🦅',
    style: '넓은 시야로 세상을 보는 사회 선생님 스타일',
    voiceName: 'Charon',
    gender: 'male',
    color: 'bg-amber-600',
    greeting: '높이 날아오르면 세상이 다르게 보이지.',
    visualDesc: 'A sharp eagle teacher wearing a pilot uniform and goggles, full body character, 2D vector illustration, confident',
    backgroundPrompt: 'A classroom high in the sky, bird eye view of the world map, blue sky background, open air feeling, 2D vector illustration'
  },
  {
    id: 't18',
    name: '플라밍고 선생님',
    avatar: '🦩',
    style: '우아하고 리듬감 넘치는 음악 선생님 스타일',
    voiceName: 'Zephyr',
    gender: 'female',
    color: 'bg-pink-400',
    greeting: '원 앤 투 앤~ 리듬에 몸을 맡겨봐!',
    visualDesc: 'A graceful flamingo teacher wearing a tutu and ballet shoes, full body character, 2D vector illustration, elegant',
    backgroundPrompt: 'A dance studio classroom with mirrors, ballet barre, pink curtains, stage lights, elegant atmosphere, 2D vector illustration'
  },
  {
    id: 't19',
    name: '너구리 선생님',
    avatar: '🦝',
    style: '뚝딱뚝딱 무엇이든 만드는 발명가 스타일',
    voiceName: 'Puck',
    gender: 'male',
    color: 'bg-stone-500',
    greeting: '헤헤, 이거 한번 조립해볼까? 신기한 게 나올 거야!',
    visualDesc: 'A mischievous raccoon teacher wearing mechanic overalls and goggles, holding a wrench, full body character, 2D vector illustration, creative',
    backgroundPrompt: 'A messy but creative workshop classroom with gears, tools, blueprints, inventions, steampunk vibe, 2D vector illustration'
  },
  {
    id: 't20',
    name: '기린 선생님',
    avatar: '🦒',
    style: '높은 곳에서 멀리 내다보는 생물 선생님 스타일',
    voiceName: 'Kore',
    gender: 'female',
    color: 'bg-yellow-400',
    greeting: '목을 길~게 빼고 자연을 관찰해보렴.',
    visualDesc: 'A tall giraffe teacher wearing a safari outfit and holding binoculars, full body character, 2D vector illustration, nature lover',
    backgroundPrompt: 'A greenhouse classroom with tall glass ceilings, tropical plants, vines, sunlight, nature observatory style, 2D vector illustration'
  },
  // New Teachers (t21 - t30)
  {
    id: 't21',
    name: '고슴도치 선생님',
    avatar: '🦔',
    style: '꼼꼼하고 논리적인 수학 선생님 스타일',
    voiceName: 'Fenrir',
    gender: 'male',
    color: 'bg-stone-600',
    greeting: '자, 여기를 보렴. 답은 언제나 논리 속에 있어.',
    visualDesc: 'A cute hedgehog teacher wearing glasses and a sweater vest, full body character, 2D vector illustration, smart look',
    backgroundPrompt: 'A math classroom with geometric shapes, ruler, compass, graph paper background, clean and organized, 2D vector illustration'
  },
  {
    id: 't22',
    name: '다람쥐 선생님',
    avatar: '🐿️',
    style: '부지런하고 활기찬 생활 지도 선생님 스타일',
    voiceName: 'Kore',
    gender: 'female',
    color: 'bg-orange-400',
    greeting: '안녕! 오늘도 도토리처럼 알찬 하루를 보내보자!',
    visualDesc: 'A cute squirrel teacher wearing a scout uniform, full body character, 2D vector illustration, energetic',
    backgroundPrompt: 'A classroom inside a hollow tree, acorns, warm lighting, wooden furniture, nature theme, 2D vector illustration'
  },
  {
    id: 't23',
    name: '하마 선생님',
    avatar: '🦛',
    style: '덩치는 크지만 마음은 부드러운 역사 선생님 스타일',
    voiceName: 'Charon',
    gender: 'male',
    color: 'bg-slate-400',
    greeting: '허허, 옛날 이야기를 들려줄게. 귀 기울여보렴.',
    visualDesc: 'A big hippo teacher wearing a traditional robe or comfortable suit, full body character, 2D vector illustration, gentle giant',
    backgroundPrompt: 'A history classroom with ancient pottery, scrolls, world map, calm atmosphere, 2D vector illustration'
  },
  {
    id: 't24',
    name: '백조 선생님',
    avatar: '🦢',
    style: '우아하고 감수성이 풍부한 문학 선생님 스타일',
    voiceName: 'Zephyr',
    gender: 'female',
    color: 'bg-sky-200',
    greeting: '아름다운 문장으로 마음을 표현해보렴.',
    visualDesc: 'A beautiful swan teacher wearing a pearl necklace, full body character, 2D vector illustration, elegant',
    backgroundPrompt: 'A classroom by a lake, willow trees, soft sunlight, poetic atmosphere, 2D vector illustration'
  },
  {
    id: 't25',
    name: '악어 선생님',
    avatar: '🐊',
    style: '유쾌하고 장난기 넘치는 체육 선생님 스타일',
    voiceName: 'Fenrir',
    gender: 'male',
    color: 'bg-green-600',
    greeting: '크하하! 몸을 움직이면 머리도 좋아진다고!',
    visualDesc: 'A funny crocodile teacher wearing a tracksuit and holding a whistle, full body character, 2D vector illustration, sporty',
    backgroundPrompt: 'An outdoor playground classroom, soccer balls, hurdles, sunny sky, energetic atmosphere, 2D vector illustration'
  },
  {
    id: 't26',
    name: '캥거루 선생님',
    avatar: '🦘',
    style: '엄마처럼 세심하게 챙겨주는 담임 선생님 스타일',
    voiceName: 'Kore',
    gender: 'female',
    color: 'bg-yellow-600',
    greeting: '우리 친구들, 주머니 속에 쏙 넣고 싶을 만큼 귀엽구나.',
    visualDesc: 'A caring kangaroo teacher with a pouch holding books, wearing an apron, full body character, 2D vector illustration, motherly',
    backgroundPrompt: 'A kindergarten classroom with soft mats, toys, warm yellow walls, cozy and safe, 2D vector illustration'
  },
  {
    id: 't27',
    name: '원숭이 선생님',
    avatar: '🐵',
    style: '호기심 많고 재치 있는 발명가 스타일',
    voiceName: 'Puck',
    gender: 'male',
    color: 'bg-amber-500',
    greeting: '우끼끼! 이건 어때? 새로운 아이디어가 떠올랐어!',
    visualDesc: 'A clever monkey teacher wearing overalls and holding a lightbulb, full body character, 2D vector illustration, creative',
    backgroundPrompt: 'A maker space classroom with tools, recycled materials, blueprints, fun and chaotic, 2D vector illustration'
  },
  {
    id: 't28',
    name: '앵무새 선생님',
    avatar: '🦜',
    style: '화려하고 말을 재미있게 하는 언어 선생님 스타일',
    voiceName: 'Zephyr',
    gender: 'female',
    color: 'bg-red-500',
    greeting: '안녕? 안녕? 목소리를 크게 내서 따라해봐!',
    visualDesc: 'A colorful parrot teacher wearing a microphone headset, full body character, 2D vector illustration, talkative',
    backgroundPrompt: 'A broadcasting studio classroom, microphones, "On Air" sign, colorful lights, lively atmosphere, 2D vector illustration'
  },
  {
    id: 't29',
    name: '치타 선생님',
    avatar: '🐆',
    style: '빠르고 핵심만 콕콕 집어주는 속성 과외 스타일',
    voiceName: 'Fenrir',
    gender: 'male',
    color: 'bg-yellow-300',
    greeting: '시간은 금이야! 빠르게 핵심만 배우자고.',
    visualDesc: 'A sleek cheetah teacher wearing running gear and a stopwatch, full body character, 2D vector illustration, fast',
    backgroundPrompt: 'A modern minimalist classroom, digital clocks, sleek desks, high-tech vibe, efficiency focused, 2D vector illustration'
  },
  {
    id: 't30',
    name: '수달 선생님',
    avatar: '🦦',
    style: '귀엽고 탐구심 강한 과학 선생님 스타일',
    voiceName: 'Kore',
    gender: 'female',
    color: 'bg-blue-400',
    greeting: '이 조개껍질의 비밀을 아니? 같이 알아보자!',
    visualDesc: 'A cute otter teacher holding a magnifying glass and a seashell, wearing a lab coat, full body character, 2D vector illustration, curious',
    backgroundPrompt: 'A riverside classroom, pebbles, water stream, nature observation tools, refreshing atmosphere, 2D vector illustration'
  },
  // Added Teachers (t31 - t40)
  {
    id: 't31',
    name: '햄스터 선생님',
    avatar: '🐹',
    style: '작지만 알찬 실과/요리 선생님 스타일',
    voiceName: 'Kore',
    gender: 'female',
    color: 'bg-orange-300',
    greeting: '볼주머니 가득 맛있는 이야기를 가져왔어!',
    visualDesc: 'A cute chubby hamster teacher wearing a tiny apron and holding a sunflower seed, full body character, 2D vector illustration, cute style',
    backgroundPrompt: 'A cozy pantry classroom filled with jars of seeds, nuts, warm wooden shelves, tiny furniture, 2D vector illustration'
  },
  {
    id: 't32',
    name: '얼룩말 선생님',
    avatar: '🦓',
    style: '질서와 규칙을 중요시하는 도덕 선생님 스타일',
    voiceName: 'Charon',
    gender: 'male',
    color: 'bg-stone-700',
    greeting: '선은 지키라고 있는 거야. 질서를 배워보자.',
    visualDesc: 'A stylish zebra teacher wearing a black and white referee shirt and glasses, full body character, 2D vector illustration, disciplined',
    backgroundPrompt: 'A traffic safety park classroom with crosswalks, traffic lights, road signs, orderly and safe, 2D vector illustration'
  },
  {
    id: 't33',
    name: '사슴 선생님',
    avatar: '🦌',
    style: '맑고 고운 심성을 가르치는 윤리 선생님 스타일',
    voiceName: 'Zephyr',
    gender: 'female',
    color: 'bg-amber-200',
    greeting: '마음을 차분하게 하고 자연의 소리를 들어보렴.',
    visualDesc: 'An elegant deer teacher with flowers on antlers, wearing a gentle dress, full body character, 2D vector illustration, soft nature',
    backgroundPrompt: 'A magical forest glade classroom with sunlight filtering through leaves, butterflies, flowers, peaceful, 2D vector illustration'
  },
  {
    id: 't34',
    name: '늑대 선생님',
    avatar: '🐺',
    style: '겉은 차갑지만 속은 따뜻한 지리 선생님 스타일',
    voiceName: 'Fenrir',
    gender: 'male',
    color: 'bg-slate-500',
    greeting: '길을 잃지 않으려면 지도를 잘 봐야 해.',
    visualDesc: 'A cool wolf teacher wearing a leather jacket and sunglasses, leaning confidently, full body character, 2D vector illustration, charismatic',
    backgroundPrompt: 'A camping site classroom under the stars, campfire, tents, night sky, adventurous atmosphere, 2D vector illustration'
  },
  {
    id: 't35',
    name: '꿀벌 선생님',
    avatar: '🐝',
    style: '부지런함과 협동을 가르치는 사회 선생님 스타일',
    voiceName: 'Puck', // Corrected voice assignment logic
    gender: 'female',
    color: 'bg-yellow-400',
    greeting: '윙윙! 우리 모두 힘을 합치면 못할 게 없어!',
    visualDesc: 'A busy bee teacher wearing a yellow and black striped sweater and antenna headband, full body character, 2D vector illustration, diligent',
    backgroundPrompt: 'A golden honeycomb classroom, hexagonal shelves filled with honey, bright yellow and warm, 2D vector illustration'
  },
  {
    id: 't36',
    name: '공작 선생님',
    avatar: '🦚',
    style: '자신감을 심어주는 연극/예술 선생님 스타일',
    voiceName: 'Charon',
    gender: 'male',
    color: 'bg-purple-600',
    greeting: '자, 너의 재능을 마음껏 펼쳐보라구!',
    visualDesc: 'A flamboyant peacock teacher showing off colorful tail feathers, holding a fan, full body character, 2D vector illustration, artistic',
    backgroundPrompt: 'A colorful stage classroom with curtains, spotlights, art supplies, theatrical atmosphere, 2D vector illustration'
  },
  {
    id: 't37',
    name: '고래 선생님',
    avatar: '🐋',
    style: '넓은 마음으로 감싸주는 상담 선생님 스타일',
    voiceName: 'Kore',
    gender: 'female',
    color: 'bg-blue-600',
    greeting: '바다처럼 넓은 마음으로 세상을 품어보렴.',
    visualDesc: 'A gentle blue whale teacher floating in air/water, wearing a sailor hat, full body character, 2D vector illustration, massive and kind',
    backgroundPrompt: 'A deep ocean classroom, coral reefs, schools of fish, blue water, peaceful and vast, 2D vector illustration'
  },
  {
    id: 't38',
    name: '개구리 선생님',
    avatar: '🐸',
    style: '날씨와 환경을 알려주는 과학 선생님 스타일',
    voiceName: 'Puck',
    gender: 'male',
    color: 'bg-green-500',
    greeting: '개굴개굴! 비가 올까? 해가 뜰까? 같이 알아보자!',
    visualDesc: 'A cheerful frog teacher wearing a yellow raincoat and rain boots, holding an umbrella, full body character, 2D vector illustration, rainy day',
    backgroundPrompt: 'A lotus pond classroom, large lily pads as desks, rain falling softly, green and fresh, 2D vector illustration'
  },
  {
    id: 't39',
    name: '나비 선생님',
    avatar: '🦋',
    style: '아름다운 변화와 성장을 돕는 미술 선생님 스타일',
    voiceName: 'Zephyr',
    gender: 'female',
    color: 'bg-purple-400',
    greeting: '너도 언젠가는 아름다운 날개를 펼치게 될 거야.',
    visualDesc: 'A beautiful butterfly teacher with large colorful wings, wearing a flowery dress, full body character, 2D vector illustration, lovely',
    backgroundPrompt: 'A flower garden classroom, giant tulips and roses, morning dew, fairy tale atmosphere, 2D vector illustration'
  },
  {
    id: 't40',
    name: '나무늘보 선생님',
    avatar: '🦥',
    style: '느리지만 꼼꼼하게 가르치는 명상 선생님 스타일',
    voiceName: 'Charon',
    gender: 'male',
    color: 'bg-stone-400',
    greeting: '천...천...히... 숨...을... 들...이...마...셔...',
    visualDesc: 'A slow relaxed sloth teacher hanging from a branch, wearing a nightcap, full body character, 2D vector illustration, chill',
    backgroundPrompt: 'A jungle canopy classroom, vines, hammocks, dappled sunlight, very slow and relaxed atmosphere, 2D vector illustration'
  }
];

export const GRADES = Object.values(GradeLevel);
